#############################################################################
# Generated by PAGE version 4.26
#  in conjunction with Tcl version 8.6
#  Jan 09, 2020 01:11:30 PM EST  platform: Linux
set vTcl(timestamp) ""


set image_list { \
    mrd_goi_png ../../../../Documents/gui/mrd-goi.png \
}
   vTcl:create_project_images $image_list   ;# In image.tcl


if {!$vTcl(borrow) && !$vTcl(template)} {

set desc "-family {Arimo} -size 10"
set vTcl(actual_gui_font_text_desc) $desc
set vTcl(actual_gui_font_text_name) [font create {*}$desc]
set desc "-family {Cousine} -size 10"
set vTcl(actual_gui_font_fixed_desc) $desc
set vTcl(actual_gui_font_fixed_name) [font create {*}$desc]
set desc "-family {Arimo} -size 10"
set vTcl(actual_gui_font_menu_desc) $desc
set vTcl(actual_gui_font_menu_name) [font create {*}$desc]
set desc "-family {Arimo} -size 10"
set vTcl(actual_gui_font_tooltip_desc) $desc
set vTcl(actual_gui_font_tooltip_name) [font create {*}$desc]
set desc "-family {Arimo} -size 10"
set vTcl(actual_gui_font_treeview_desc) $desc
set vTcl(actual_gui_font_treeview_name) [font create {*}$desc]
set vTcl(actual_gui_bg) #d9d9d9
set vTcl(actual_gui_fg) #000000
set vTcl(actual_gui_analog) #ececec
set vTcl(actual_gui_menu_analog) #ececec
set vTcl(actual_gui_menu_bg) #d9d9d9
set vTcl(actual_gui_menu_fg) #000000
set vTcl(complement_color) #d9d9d9
set vTcl(analog_color_p) #d9d9d9
set vTcl(analog_color_m) #ececec
set vTcl(active_fg) #000000
set vTcl(actual_gui_menu_active_bg)  #ececec
set vTcl(active_menu_fg) #000000
}




proc vTclWindow.top42 {base} {
    global vTcl
    if {$base == ""} {
        set base .top42
    }
    if {[winfo exists $base]} {
        wm deiconify $base; return
    }
    set top $base
    ###################
    # CREATING WIDGETS
    ###################
    vTcl::widgets::core::toplevel::createCmd $top -class Toplevel \
        -menu "$top.m49" -background #d6d8ab -highlightcolor #5e5e5e 
    wm focusmodel $top passive
    wm geometry $top 996x638+360+52
    update
    # set in toplevel.wgt.
    global vTcl
    global img_list
    set vTcl(save,dflt,origin) 0
    wm maxsize $top 1351 738
    wm minsize $top 1 1
    wm overrideredirect $top 0
    wm resizable $top 1 1
    wm deiconify $top
    wm title $top "MInIstry of rural development"
    vTcl:DefineAlias "$top" "Toplevel1" vTcl:Toplevel:WidgetProc "" 1
    set site_3_0 $top.m49
    menu $site_3_0 \
        -activebackground #aaaaaa -activeforeground #000000 \
        -background #cdd8d3 -font $vTcl(actual_gui_font_menu_desc) \
        -foreground $vTcl(pr,menufgcolor) -tearoff 0 
    label $top.lab56 \
        -background #d6d8ab -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -image mrd_goi_png 
    vTcl:DefineAlias "$top.lab56" "Label1" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab57 \
        -activebackground #ffffff -background #ffffff -font TkDefaultFont \
        -foreground $vTcl(actual_gui_fg) -highlightbackground #ffffff 
    vTcl:DefineAlias "$top.lab57" "Label2" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent59 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$top.ent59" "Entry1" vTcl:WidgetProc "Toplevel1" 1
    entry $top.ent60 \
        -background white -font $vTcl(actual_gui_font_fixed_desc) \
        -foreground $vTcl(actual_gui_fg) -insertbackground black 
    vTcl:DefineAlias "$top.ent60" "Entry2" vTcl:WidgetProc "Toplevel1" 1
    label $top.lab62 \
        -background #d6d8ab -font {-family {Arimo} -size 10 -weight bold} \
        -foreground $vTcl(actual_gui_fg) -text Prediction 
    vTcl:DefineAlias "$top.lab62" "Label5" vTcl:WidgetProc "Toplevel1" 1
    button $top.but63 \
        -background #d5d8b5 \
        -font {-family {Arimo} -size 10 -weight bold -slant italic} \
        -foreground $vTcl(actual_gui_fg) -highlightcolor black \
        -text {Add Image} 
    vTcl:DefineAlias "$top.but63" "Button1" vTcl:WidgetProc "Toplevel1" 1
    ###################
    # SETTING GEOMETRY
    ###################
    place $top.lab56 \
        -in $top -x -10 -y 50 -width 515 -relwidth 0 -height 650 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab57 \
        -in $top -x 420 -y 130 -width 475 -relwidth 0 -height 250 \
        -relheight 0 -anchor nw -bordermode ignore 
    place $top.ent59 \
        -in $top -x 610 -y 410 -width 156 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.ent60 \
        -in $top -x 610 -y 460 -width 156 -relwidth 0 -height 32 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.lab62 \
        -in $top -x 480 -y 460 -width 75 -relwidth 0 -height 30 -relheight 0 \
        -anchor nw -bordermode ignore 
    place $top.but63 \
        -in $top -x 470 -y 410 -anchor nw -bordermode ignore 

    vTcl:FireEvent $base <<Ready>>
}

set btop ""
if {$vTcl(borrow)} {
    set btop .bor[expr int([expr rand() * 100])]
    while {[lsearch $btop $vTcl(tops)] != -1} {
        set btop .bor[expr int([expr rand() * 100])]
    }
}
set vTcl(btop) $btop
Window show .
Window show .top42 $btop
if {$vTcl(borrow)} {
    $btop configure -background plum
}

